### PR TITLE
Add pkg_binds and pkg_binds_optional snippets

### PR DESCRIPTION
**Pull request by reset**
This PR is a companion to:
* https://github.com/habitat-sh/habitat/pull/1760

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by eeyun** [comment]
Looks like we've got namespace overlap on one of the new snippets. Would you be willing to update your pr to change the `(short)` for `pkg_build_deps` from `pb` to `pbd` ?

**Comment by reset** [comment]
@eeyun good catch! Updated it

**Pull request merged**
